export const SET_NEWS = 'SET_NEWS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CLOSE_MODAL_SIGNUP = 'CLOSE_MODAL_SIGNUP';
export const CLOSE_VERIFY_MODAL_SIGNUP = 'CLOSE_VERIFY_MODAL_SIGNUP';

export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLOSE_MODAL_ERROR_LOGIN = 'CLOSE_MODAL_ERROR_LOGIN';