export const SET_NEWS = 'SET_NEWS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CLOSE_MODAL_SIGNUP = 'CLOSE_MODAL_SIGNUP';