export const SET_NEWS = 'SET_NEWS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CLOSE_MODAL_SIGNUP = 'CLOSE_MODAL_SIGNUP';
export const CLOSE_VERIFY_MODAL_SIGNUP = 'CLOSE_VERIFY_MODAL_SIGNUP';
export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLOSE_MODAL_ERROR_LOGIN = 'CLOSE_MODAL_ERROR_LOGIN';
export const NAVIGATE_AFTER_LOGIN_START = 'NAVIGATE_AFTER_LOGIN_START';
export const NAVIGATE_AFTER_LOGIN_SUCCESS = 'NAVIGATE_AFTER_LOGIN_SUCCESS';
export const NAVIGATE_AFTER_LOGIN_FAILED = 'NAVIGATE_AFTER_LOGIN_FAILED';

export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAILED = 'RECOVER_PASSWORD_FAILED';
export const VERIFY_RECOVER_PASSWORD_START = 'VERIFY_RECOVER_PASSWORD_START';
export const VERIFY_RECOVER_PASSWORD_SUCCESS = 'VERIFY_RECOVER_PASSWORD_SUCCESS';
export const VERIFY_RECOVER_PASSWORD_FAILED = 'VERIFY_RECOVER_PASSWORD_FAILED';
export const CLOSE_MODAL_ERROR_RECOVER_PASSWORD = 'CLOSE_MODAL_ERROR_RECOVER_PASSWORD';
export const RECOVER_PROCESS_START = 'RECOVER_PROCESS_START';
export const RECOVER_PROCESS_SUCCESS = 'RECOVER_PROCESS_SUCCESS';
export const RECOVER_PROCESS_FAILED = 'RECOVER_PROCESS_FAILED';
export const CLOSE_RECOVER_PROCESS_MODAL = 'CLOSE_RECOVER_PROCESS_MODAL';

export const VERIFY_AFTER_LOGIN_START = 'VERIFY_AFTER_LOGIN_START';
export const VERIFY_AFTER_LOGIN_SUCCESS = 'VERIFY_AFTER_LOGIN_SUCCESS';
export const VERIFY_AFTER_LOGIN_FAIL = 'VERIFY_AFTER_LOGIN_FAIL';
export const CLOSE_VERIFY_MODAL_AFTER_LOGIN = 'CLOSE_VERIFY_MODAL_AFTER_LOGIN';

export const SET_LOCATIONS = 'SET_LOCATIONS';
export const FETCH_LOCATIONS_FAIL = 'FETCH_LOCATIONS_FAIL';

export const TESTING_REGISTRATION_START = 'TESTING_REGISTRATION_START';
export const TESTING_REGISTRATION_SUCCESS = 'TESTING_REGISTRATION_SUCCESS';
export const TESTING_REGISTRATION_FAIL = 'TESTING_REGISTRATION_FAIL';

export const SUBMIT_MEDICALINFO_START = 'SUBMIT_MEDICALINFO_START';
export const SUBMIT_MEDICALINFO_SUCCESS = 'SUBMIT_MEDICALINFO_SUCCESS';
export const SUBMIT_MEDICALINFO_FAIL = 'SUBMIT_MEDICALINFO_FAIL';

export const CLOSE_MODAL_TESTING_REGISTRATION = 'CLOSE_MODAL_TESTING_REGISTRATION';

export const SET_DISABLE_DATES = 'SET_DISABLE_DATES';
export const FETCH_DISABLE_DATES_FAIL = 'FETCH_DISABLE_DATES_FAIL';

export const GET_TESTING_INFORMATION_START = 'GET_TESTING_INFORMATION_START';
export const GET_TESTING_INFORMATION_SUCCESS = 'GET_TESTING_INFORMATION_SUCCESS';
export const GET_TESTING_INFORMATION_FAIL = 'GET_TESTING_INFORMATION_FAIL';

export const CHECKIN_LOCATION_START = 'CHECKIN_LOCATION_START';
export const CHECKIN_LOCATION_SUCCESS = 'CHECKIN_LOCATION_SUCCESS';
export const CHECKIN_LOCATION_FAIL = 'CHECKIN_LOCATION_FAIL';
export const CLOSE_MODAL_CHECKIN_LOCATION = 'CLOSE_MODAL_CHECKIN_LOCATION';
